include:
#  - board: nice_nano_v2
#    shield: cheapinov2
#    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: cheapis
    snippet: studio-rpc-usb-uart
  ## reset firmware
  - board: nice_nano_v2
    shield: settings_reset